import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = { title: "Privacy Policy", description: "How ResumeStudio handles résumé, account, AI, purchase, voice, iCloud, and Review Room data." };

export default function PrivacyPage() {
  return <main>
    <header className="site-header"><Link className="brand" href="/"><span className="brand-mark">CV</span><span>Resume<span className="accent">Studio</span></span></Link><nav><Link href="/support">Support</Link><Link href="/privacy">Privacy</Link></nav></header>
    <article className="document">
      <p className="eyebrow">PRIVACY POLICY</p><h1>Your work stays yours.</h1><p className="updated">Effective 16 July 2026</p>
      <section><h2>Summary</h2><p>ResumeStudio is an offline-first career workspace. Résumé documents, applications, cover letters, career evidence, contacts, offers, and interview history are stored on your device. Optional features send limited data only when you choose to use them.</p></section>
      <section><h2>Data stored on your device</h2><ul><li>Résumés, photos, layouts, versions, cover letters, and exports.</li><li>Applications, interviews, voice-practice recordings and transcripts, offers, contacts, and career evidence.</li><li>AI results, processing history, preferences, and the last verified StoreKit entitlement needed for secure offline access.</li></ul><p>Voice recordings remain local. ResumeStudio sends the transcript—not the raw recording—when you request AI feedback.</p></section>
      <section><h2>iCloud</h2><p>If you enable document sync, ResumeStudio stores an encrypted-in-transit workspace archive in your private iCloud container under your Apple Account. Apple provides the iCloud service. You can disable sync or erase the archive from Account and backup.</p></section>
      <section><h2>Account and Firebase data</h2><p>ResumeStudio creates a protected anonymous Firebase account so allowances and saved AI results can work without mandatory registration. If you choose email or Sign in with Apple, Firebase stores the account identifier and email address where provided.</p><p>Firebase may store saved AI results, AI-credit usage, referral records, entitlement verification results, and hosted Review Room metadata. These records are used only for app functionality, security, fraud prevention, and customer support.</p></section>
      <section><h2>AI processing</h2><p>AI runs only after you select an AI action. Requests go through ResumeStudio’s Firebase backend to OpenAI. The backend uses structured responses and requests that OpenAI not store the response for model training or later retrieval.</p><p>Résumé-writing requests exclude names, phone numbers, email addresses, references, profile photographs, attached source files, interview links, interviewer names, and private source URLs. The minimum relevant résumé or career evidence is sent for the selected task. You can pause AI and exclude Evidence Vault items in Privacy Centre.</p></section>
      <section><h2>Review Rooms</h2><p>Publishing a Review Room uploads the exact PDF you selected, which may contain personal information you placed in that PDF. The PDF is protected by an unguessable link and access code, expires within 31 days, and can be revoked or deleted immediately by its owner. Reviewer names and comments are stored with the room.</p></section>
      <section><h2>Purchases</h2><p>Apple processes purchases and payment details. ResumeStudio receives signed transaction information such as product identifier, status, purchase date, and expiration date to unlock access and enforce AI allowances. ResumeStudio does not receive card or bank details.</p></section>
      <section><h2>Data sharing and tracking</h2><p>ResumeStudio does not sell personal data, show third-party advertising, or track you across other companies’ apps and websites. Service providers receive data only to provide authentication, cloud functions, AI processing, purchase verification, iCloud sync, or Review Rooms.</p></section>
      <section><h2>Retention and deletion</h2><p>On-device data remains until you delete it or remove the app. iCloud data remains until you erase the archive. Saved AI work remains in Firebase until you delete it or your account. Review Room access ends on expiry or revocation; deleting a room or account immediately removes its hosted PDF and comments.</p><p>Use Settings → Account and backup → Delete account and data to delete Firebase Auth, saved AI results, referral and credit records, and Review Rooms. You can separately erase local and iCloud workspace data.</p></section>
      <section><h2>Children and changes</h2><p>ResumeStudio is not directed to children under 13. This policy may change when app behavior or legal requirements change; the effective date above will be updated.</p></section>
      <section><h2>Contact</h2><p>The public support email will be inserted here before launch. Questions and deletion concerns can also be initiated from the app’s Account and backup screen.</p></section>
    </article><footer><span>© 2026 Halalisani Mbanjwa</span><Link href="/support">Support</Link></footer>
  </main>;
}
